import 'package:get/get.dart';

class AppTranslation extends Translations {
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          //home_page
          "Welcome": "Welcome",
          "Take Picture": "Take Picture",
          "Plant Encyclopedia": "Plant Encyclopedia",
          "History": "History",

          //take_pic

          "Choose an option": "Choose an option",
          "Camera": "Camera",
          "Gallery": "Gallery",

          //"Plant Encyclopedia": "Plant Encyclopedia",
          "No plants found.": "No plants found.",

          //History

          "History of Plants": "History of Plants",
          "No saved plants": "No saved plants",

          //identified
          "Plant Identified!": "Plant Identified!",
          "Tomato": "Tomato",
          "Detect Disease": "Detect Disease",

          //disease_detected

          "Plant Identified & \nDisease Detected!":
              "Plant Identified & \nDisease Detected!",

          //identify_and_detect

          "Identify Plant": "Identify Plant",

          //language_selection

          "Language Selection": "Language Selection",
          "English": "English",
          "Urdu": "Urdu",

          //no_disease

          "No Disease Present!": "No Disease Present!",

          //no_plant_found
          "Plant Not Found!": "Plant Not Found!",

          //plant_detail
          "Plant Details": "Plant Details",

          //plant_detail_widget

          "Scientific Name": "Scientific Name",
          "Description": "Description",
          "Diseases": "Diseases",
          "Disease Description": "Disease Description",
          "Treatments": "Treatments",

          //data

          "Solanum lycopersicum": "Solanum lycopersicum",
          //tomato desc
          "1. The tomato plant (Solanum lycopersicum) is a popular and versatile plant cultivated worldwide for its delicious and nutritious fruit.\n\n2. Tomato plants have a sprawling growth habit with vine-like stems that require support. The leaves are compound and typically green with a slightly hairy texture. The flowers are small, yellow, and usually self-pollinating.\n\n3. Tomatoes come in various sizes, shapes, and colors depending on the variety. The fruits develop after successful pollination and can be harvested when they reach maturity.\n\n4. To cultivate tomato plants successfully, it\\'s essential to consider factors such as soil preparation, watering, fertilizing, and pest control. Staking or pruning techniques may also be necessary for optimal growth and fruit production.":
              "1. The tomato plant (Solanum lycopersicum) is a popular and versatile plant cultivated worldwide for its delicious and nutritious fruit.\n\n2. Tomato plants have a sprawling growth habit with vine-like stems that require support. The leaves are compound and typically green with a slightly hairy texture. The flowers are small, yellow, and usually self-pollinating.\n\n3. Tomatoes come in various sizes, shapes, and colors depending on the variety. The fruits develop after successful pollination and can be harvested when they reach maturity.\n\n4. To cultivate tomato plants successfully, it\\'s essential to consider factors such as soil preparation, watering, fertilizing, and pest control. Staking or pruning techniques may also be necessary for optimal growth and fruit production.",

          "Late blight": "Late blight",
          //late blight description
          "1. Late blight is a destructive and highly contagious fungal disease that primarily affects tomatoes and potatoes. It is caused by the pathogen Phytophthora infestans.\n\n2. The disease commonly appears as dark, water-soaked lesions on leaves, stems, and fruits of infected plants. These lesions may rapidly enlarge, turn brown, and develop a fuzzy white mold growth on the undersides during humid conditions.\n\n3. Late blight thrives in cool and wet conditions, particularly during periods of high humidity and temperatures ranging from 50 to 80°F (10 to 27°C). Spores of the pathogen can spread rapidly through wind, rain, or movement of infected plant material.\n\n4. It is crucial to promptly identify and manage late blight to prevent severe crop damage. Control measures include removing and destroying infected plants, applying fungicides, maintaining proper spacing between plants, promoting good air circulation, and practicing crop rotation.":
              "1. Late blight is a destructive and highly contagious fungal disease that primarily affects tomatoes and potatoes. It is caused by the pathogen Phytophthora infestans.\n\n2. The disease commonly appears as dark, water-soaked lesions on leaves, stems, and fruits of infected plants. These lesions may rapidly enlarge, turn brown, and develop a fuzzy white mold growth on the undersides during humid conditions.\n\n3. Late blight thrives in cool and wet conditions, particularly during periods of high humidity and temperatures ranging from 50 to 80°F (10 to 27°C). Spores of the pathogen can spread rapidly through wind, rain, or movement of infected plant material.\n\n4. It is crucial to promptly identify and manage late blight to prevent severe crop damage. Control measures include removing and destroying infected plants, applying fungicides, maintaining proper spacing between plants, promoting good air circulation, and practicing crop rotation.",
          //late blight treatement
          "1. Promptly remove and destroy any infected plants, including leaves, stems, and fruits. This helps prevent the spread of the disease.\n\n2. Apply appropriate fungicides according to the manufacturer's instructions. Fungicides containing active ingredients like chlorothalonil, mancozeb, or copper can be effective against late blight. Follow the recommended application rates and timings.\n\n3. Ensure proper spacing between plants to promote good air circulation. This reduces humidity levels and creates an environment less favorable for the development and spread of late blight.\n\n4. Practice crop rotation by avoiding planting tomatoes or potatoes in the same location for consecutive years. This helps break the disease cycle as the pathogen cannot survive without a suitable host plant.\n\nRemember to regularly monitor your plants for any signs of late blight and take action promptly if detected. Early intervention is crucial to prevent severe damage and minimize the spread of the disease.":
              "1. Promptly remove and destroy any infected plants, including leaves, stems, and fruits. This helps prevent the spread of the disease.\n\n2. Apply appropriate fungicides according to the manufacturer's instructions. Fungicides containing active ingredients like chlorothalonil, mancozeb, or copper can be effective against late blight. Follow the recommended application rates and timings.\n\n3. Ensure proper spacing between plants to promote good air circulation. This reduces humidity levels and creates an environment less favorable for the development and spread of late blight.\n\n4. Practice crop rotation by avoiding planting tomatoes or potatoes in the same location for consecutive years. This helps break the disease cycle as the pathogen cannot survive without a suitable host plant.\n\nRemember to regularly monitor your plants for any signs of late blight and take action promptly if detected. Early intervention is crucial to prevent severe damage and minimize the spread of the disease.",

          "Peach": "Peach",
          "Rose": "Rose",
          "Grape": "Grape",
          "Prunus persica": "Prunus persica",
          "peach_desc":
              "1. Peaches are juicy and delicious fruits that belong to the Prunus genus.\n\n2. They are native to China and are now cultivated in various parts of the world.\n\n3.Peaches have a soft, fuzzy skin, and their flesh is sweet and aromatic.\n\n4. They come in different varieties, including clingstone and freestone.\n\n5. Peaches are rich in vitamins A and C and are a good source of dietary fiber.",
          "Bacterial spot": "Bacterial spot",
          "bacterial_spot_desc":
              "1. Bacterial spot is a common and destructive disease that affects peach trees. It is caused by the bacterium Xanthomonas arboricola pv. pruni.\n\n2. The disease typically manifests as small, dark spots on the leaves, fruits, and twigs of infected peach trees. These spots may have a water-soaked appearance and can enlarge over time. As the disease progresses, the spots develop a raised, corky texture and may lead to premature leaf drop and fruit rot.\n\n3. Bacterial spot thrives in warm and humid conditions, especially during periods of rainfall or overhead irrigation. The bacterium can overwinter in infected buds, bark, and cankers, leading to recurring infections in subsequent seasons.\n\n4. Proper identification and management of bacterial spot are crucial to minimize its impact on peach tree health and fruit quality.",
          "bacterial_spot_treat":
              "1. Prune and remove infected plant parts, including branches, twigs, and fruit showing symptoms of bacterial spot. Dispose of the pruned material away from the orchard to prevent further spread.\n\n2. Apply copper-based bactericides during the dormant season to protect against bacterial spot infection. Follow the manufacturer's instructions for proper application rates and timings.\n\n3. Implement cultural practices that promote good tree health, such as proper spacing, pruning to improve air circulation, and avoiding excessive nitrogen fertilization. These practices help create an environment less favorable for bacterial spot development.\n\n4. Avoid overhead irrigation, as wetting the foliage increases the risk of bacterial spot infection. Instead, utilize drip irrigation or other methods that minimize moisture on the leaves and fruit.\n\n5. If the disease pressure is high, consider applying protective copper-based sprays during the growing season. These sprays provide additional control against bacterial spot when applied preventatively or at the first signs of the disease.\n\nRemember to consult with local agricultural extension offices or experts for specific recommendations and guidance tailored to your region and orchard management practices.",

          "Rosa": "Rosa",
          "rose_desc":
              "1. Roses are popular flowering plants that belong to the Rosa genus.\n\n2. They come in a wide range of colors, sizes, and fragrances.\n\n3. Roses have thorny stems and attractive, layered petals.\n\n4. They are widely cultivated for ornamental purposes and are often used in gardens and floral arrangements.\n\n5. Roses have symbolic meanings and are associated with love, beauty, and romance.",
          "Black spot": "Black spot",
          "black_spot_desc":
              "1. Rose black spot is a common and widespread fungal disease that affects roses. It is caused by the fungus Diplocarpon rosae.\n\n2. The disease typically appears as black or dark brown spots on the leaves of infected roses. These spots may start small but gradually increase in size, causing the affected leaves to turn yellow and eventually drop prematurely. In severe cases, the black spots can coalesce, leading to defoliation and weakening of the rose plant.\n\n3. Rose black spot thrives in warm and humid conditions, especially when foliage remains wet for prolonged periods. The fungus overwinters on fallen leaves and can spread through splashing water, rain, or wind-dispersed spores.\n\n4. Effective management of rose black spot involves a combination of cultural practices and fungicidal treatments. Early detection and consistent control measures are essential to maintain healthy roses.",
          "black_spot_treat":
              "1. Prune and remove any infected leaves, canes, or plant debris from around the rose bushes. Proper sanitation helps reduce the source of inoculum and limits the spread of the disease.\n\n2. Ensure good air circulation around the rose plants by pruning for better spacing and removing any overcrowded branches. This promotes faster drying of the foliage and reduces the favorable conditions for black spot development.\n\n3. Water the roses at the base, avoiding overhead irrigation. Wet foliage can facilitate the spread of the fungus. Mulching around the plants can also help maintain soil moisture and prevent splashing of spores onto the leaves.\n\n4. Apply fungicides specifically labeled for black spot control on roses. Follow the manufacturer's instructions regarding application rates and timings. Begin spraying preventatively, especially during periods of high humidity or when black spot is known to be present.\n\n5. Consider planting resistant rose varieties that are less susceptible to black spot. These varieties can provide a level of natural resistance, reducing the need for frequent fungicidal treatments.\n\nConsult with local rose experts or garden centers for specific fungicide recommendations and guidelines tailored to your region and rose cultivars.",

          "Vitis": "Vitis",
          "grape_desc":
              "1. Grapes are fruits that grow on vines of the Vitis genus.\n\n2. They are native to the Mediterranean region and are now cultivated worldwide.\n\n3. Grapes come in various colors, including green, red, and purple.\n\n4. They are often consumed fresh or used for making wines, juices, and raisins.\n\n5. Grapes are a rich source of antioxidants, vitamins, and minerals.",
          "Black rot": "Black rot",
          "black_rot_desc":
              "1. Grape black rot is a fungal disease caused by the pathogen Guignardia bidwellii. It affects various grape cultivars and can cause significant damage to both foliage and fruit.\n\n2. The disease manifests as small, dark brown or black circular lesions on grape berries, leaves, and stems. These lesions may enlarge and become sunken, with a characteristic 'mummified' appearance. Infected berries often shrivel and turn black, resulting in severe fruit loss.\n\n3. Grape black rot thrives in warm and humid climates. The fungus overwinters in infected plant material, such as dried berries and canes, and releases spores in spring during rainfall or high humidity.\n\n4. Proper identification, monitoring, and management of grape black rot are essential to protect vineyards and preserve grape yield and quality.",
          "black_rot_treat":
              "1. Prune and remove any infected grape clusters, leaves, and canes from the vineyard. Destroy the pruned material to prevent the spread of the disease. Proper sanitation practices help reduce the inoculum source.\n\n2. Implement canopy management techniques that promote good air circulation and sunlight penetration into the grapevine canopy. This reduces humidity levels and creates an environment less favorable for black rot development.\n\n3. Apply appropriate fungicides during critical growth stages to protect against grape black rot. Fungicides containing active ingredients like captan, myclobutanil, or mancozeb are commonly used. Follow the manufacturer's instructions for application rates and timings.\n\n4. Remove weeds and grasses around the base of the grapevines, as they can harbor the black rot fungus. Maintaining weed-free zones reduces the chances of infection and improves air circulation.\n\n5. Practice regular monitoring of grape clusters, leaves, and stems for early signs of black rot. Promptly remove and destroy any infected plant material to prevent further spread.\n\nConsult with local viticulture experts or agricultural extension offices for specific fungicide recommendations and guidelines tailored to your grape cultivars and regional conditions.",
          "ٹماٹر": "Tomato",
          "سولینم لائکوپرسیکم": "Solanum lycopersicum",
          //tomato descr
          "1. ٹماٹر کا پودا (Solanum lycopersicum) ایک مقبول اور ورسٹائل پودا ہے جو دنیا بھر میں اپنے مزیدار اور غذائیت سے بھرپور پھل کے لئے کاشت کیا جاتا ہے۔\n\n2. ٹماٹر کے پودوں میں انگور جیسے تنوں کے ساتھ بہت زیادہ نشوونما کی عادت ہوتی ہے جن میں مدد کی ضرورت ہوتی ہے۔ پتے کمپاؤنڈ ہوتے ہیں اور عموماً ہلکے بالوں والی ساخت کے ساتھ سبز ہوتے ہیں۔ پھول چھوٹے، پیلے رنگ کے ہوتے ہیں اور عموماً خود آلودگی کرنے والے ہوتے ہیں۔\n\n3. ٹماٹر مختلف سائز، سائز، اور مختلف قسم کے لحاظ سے رنگوں میں آتے ہیں. پھل کامیاب زراعت کے بعد نشوونما پاتے ہیں اور جب یہ پختگی تک پہنچ جاتے ہیں تو کاشت کی جا سکتی ہے۔\n\n4. ٹماٹر کے پودوں کو کامیابی سے کاشت کرنے کے لئے، مٹی کی تیاری، پانی، کھاد اور کیڑوں پر قابو پانے جیسے عوامل پر غور کرنا ضروری ہے۔ زیادہ سے زیادہ نشوونما اور پھلوں کی پیداوار کے لئے سٹاکنگ یا کٹائی کی تکنیک بھی ضروری ہو سکتی ہے۔":
              "1. The tomato plant (Solanum lycopersicum) is a popular and versatile plant cultivated worldwide for its delicious and nutritious fruit.\n\n2. Tomato plants have a sprawling growth habit with vine-like stems that require support. The leaves are compound and typically green with a slightly hairy texture. The flowers are small, yellow, and usually self-pollinating.\n\n3. Tomatoes come in various sizes, shapes, and colors depending on the variety. The fruits develop after successful pollination and can be harvested when they reach maturity.\n\n4. To cultivate tomato plants successfully, it's essential to consider factors such as soil preparation, watering, fertilizing, and pest control. Staking or pruning techniques may also be necessary for optimal growth and fruit production.",
          "لیٹ بلائٹ": "Late blight",
          //late blight desc
          "1. لیٹ بلائٹ ایک تباہ کن اور انتہائی متعدی فطر کی بیماری ہے جو بنیادی طور پر ٹماٹر اور آلو کو متاثر کرتی ہے۔ یہ مرض زا فائٹوفتھورا انفیسٹنس کی وجہ سے ہوتا ہے۔\n\n2. مرض عام طور پر انفیکشن زدہ پودوں کے پتوں، تنوں اور پھلوں پر گہرے، پانی میں بھیگے ہوئے زخموں کے طور پر ظاہر ہوتا ہے۔ یہ زخم تیزی سے بڑے ہو سکتے ہیں، بھورے ہو سکتے ہیں اور نم حالات کے دوران نچلے حصے پر فجی سفید پھپھوندی کی نشوونما پیدا کرتے ہیں۔\n\n3. دیر سے مرجھانا ٹھنڈے اور گیلے حالات میں پھولتا ہے، خاص طور پر زیادہ نمی اور درجہ حرارت 50 سے 80° F (10 سے 27 ڈگری سینٹی گریڈ) کے دوران ہوتا ہے۔ مرض زا کے تخمک ہوا، بارش یا متاثرہ پودے کے مواد کی نقل و حرکت سے تیزی سے پھیل سکتے ہیں۔\n\n4. فصل کے شدید نقصان سے بچنے کے لئے فوری طور پر مرجھانے اور دیر سے مرجھانے کا انتظام کرنا انتہائی اہم ہے۔ کنٹرول کے اقدامات میں انفیکشن زدہ پودوں کو ہٹانا اور تباہ کرنا، فطر کش ادویات لگانا، پودوں کے درمیان مناسب وقفہ برقرار رکھنا، اچھی ہوا کی گردش کو فروغ دینا اور فصل کی گردش کی مشق شامل ہیں۔":
              "1. Late blight is a destructive and highly contagious fungal disease that primarily affects tomatoes and potatoes. It is caused by the pathogen Phytophthora infestans.\n\n2. The disease commonly appears as dark, water-soaked lesions on leaves, stems, and fruits of infected plants. These lesions may rapidly enlarge, turn brown, and develop a fuzzy white mold growth on the undersides during humid conditions.\n\n3. Late blight thrives in cool and wet conditions, particularly during periods of high humidity and temperatures ranging from 50 to 80°F (10 to 27°C). Spores of the pathogen can spread rapidly through wind, rain, or movement of infected plant material.\n\n4. It is crucial to promptly identify and manage late blight to prevent severe crop damage. Control measures include removing and destroying infected plants, applying fungicides, maintaining proper spacing between plants, promoting good air circulation, and practicing crop rotation.",
          //late blight treat

          "1. کسی بھی متاثرہ پودوں کو فوری طور پر ہٹا دیں اور تباہ کر دیں، بشمول پتے، تنوں اور پھلوں کو تباہ کر دیں۔ اس سے بیماری کے پھیلاؤ کو روکنے میں مدد ملتی ہے۔\n\n2. صنعت کار کی ہدایات کے مطابق مناسب فطر کش ادویات کا اطلاق کریں۔ کلوروتھالونل، مینکوزیب یا تانبے جیسے فعال اجزاء پر مشتمل فطر کش ادویات دیر سے مرجھانے کے خلاف مؤثر ثابت ہو سکتی ہیں۔ سفارش کی درخواست کی شرح اور اوقات پر عمل کریں.\n\n3. اچھی ہوا کی گردش کو فروغ دینے کے لئے پودوں کے درمیان مناسب وقفہ کو یقینی بنائیں. یہ نمی کی سطح کو کم کرتا ہے اور دیر سے مرجھانے کی نشوونما اور پھیلاؤ کے لئے کم سازگار ماحول پیدا کرتا ہے.\n\n4. مسلسل برسوں تک ایک ہی مقام پر ٹماٹر یا آلو لگانے سے گریز کر کے فصل کی گردش کی مشق کریں۔ یہ بیماری کے چکر کو توڑنے میں مدد کرتا ہے کیونکہ مرض زا کسی مناسب میزبان پودے کے بغیر زندہ نہیں رہ سکتا۔\n\nباقاعدگی سے دیر سے بلائٹ کے کسی بھی علامات کے لئے اپنے پودوں کی نگرانی اور پتہ چلا ہے تو فوری طور پر کارروائی کرنے کے لئے یاد رکھیں. شدید نقصان سے بچنے اور بیماری کے پھیلاؤ کو کم کرنے کے لیے ابتدائی مداخلت انتہائی اہم ہے۔":
              "1. Promptly remove and destroy any infected plants, including leaves, stems, and fruits. This helps prevent the spread of the disease.\n\n2. Apply appropriate fungicides according to the manufacturer's instructions. Fungicides containing active ingredients like chlorothalonil, mancozeb, or copper can be effective against late blight. Follow the recommended application rates and timings.\n\n3. Ensure proper spacing between plants to promote good air circulation. This reduces humidity levels and creates an environment less favorable for the development and spread of late blight.\n\n4. Practice crop rotation by avoiding planting tomatoes or potatoes in the same location for consecutive years. This helps break the disease cycle as the pathogen cannot survive without a suitable host plant.\n\nRemember to regularly monitor your plants for any signs of late blight and take action promptly if detected. Early intervention is crucial to prevent severe damage and minimize the spread of the disease.",

          "آڑو": "Peach",
          "گلاب": "Rose",
          "انگور": "Grape",
          "پرونس پرسیکا": "Prunus persica",

          //peach desc
          "1. آڑو رسیلی اور مزیدار پھل ہیں جو پرونس جینس سے تعلق رکھتے ہیں.\n\n2. یہ چین کے مقامی ہیں اور اب دنیا کے مختلف حصوں میں کاشت کی جاتی ہے۔\n\n3. پیچ ایک نرم، فجی جلد ہے، اور ان کا گوشت میٹھا اور کھشبودار ہے.\n\n4. یہ مختلف قسموں میں آتے ہیں جن میں کلنگسٹون اور فریسٹون شامل ہیں۔\n\n5. آڑو وٹامن اے اور سی میں امیر ہیں اور غذائی فائبر کا ایک اچھا ذریعہ ہیں.":
              "1. Peaches are juicy and delicious fruits that belong to the Prunus genus.\n\n2. They are native to China and are now cultivated in various parts of the world.\n\n3. Peaches have a soft, fuzzy skin, and their flesh is sweet and aromatic.\n\n4. They come in different varieties, including clingstone and freestone.\n\n5. Peaches are rich in vitamins A and C and are a good source of dietary fiber.",

          "بیکٹیریل اسپاٹ": "Bacterial spot",

          //bacterial_spot_desc
          "1. بیکٹیریل دھبے ایک عام اور تباہ کن بیماری ہے جو آڑو کے درختوں کو متاثر کرتی ہے۔ یہ بیکٹیریم زینتھوموناس آربوریکولا پی وی پرانی کی وجہ سے ہوتا ہے۔\n\n2. بیماری عموماً پتوں، پھلوں اور متاثرہ آڑو کے درختوں پر چھوٹے، سیاہ دھبوں کے طور پر ظاہر ہوتی ہے۔ ان دھبوں میں پانی میں بھیگے ہوئے ظہور ہو سکتے ہیں اور وقت کے ساتھ ساتھ بڑے ہو سکتے ہیں۔ جیسے جیسے مرض بڑھتا ہے، دھبے ابھرتی ہوئی، کارکی ساخت بنتے ہیں اور پتے کے قبل از وقت گرنے اور پھلوں کی سڑاند کا سبب بنتے ہیں۔\n\n3. بیکٹیریل دھبے گرم اور نم حالات میں پھولتے ہیں، خاص طور پر بارش یا زیادہ آبپاشی کے دوران۔ بیکٹیریم انفیکشن زدہ کلیوں، چھال اور کینکروں میں سردیاں گزار سکتا ہے جس سے بعد کے موسموں میں بار بار ہونے والے انفیکشنز پیدا ہوتے ہیں۔\n\n4. آڑو کے درختوں کی صحت اور پھل کے معیار پر اس کے اثرات کو کم کرنے کے لئے بیکٹیریل دھبوں کی مناسب شناخت اور انتظام اہم ہے۔":
              "1. Bacterial spot is a common and destructive disease that affects peach trees. It is caused by the bacterium Xanthomonas arboricola pv. pruni.\n\n2. The disease typically manifests as small, dark spots on the leaves, fruits, and twigs of infected peach trees. These spots may have a water-soaked appearance and can enlarge over time. As the disease progresses, the spots develop a raised, corky texture and may lead to premature leaf drop and fruit rot.\n\n3. Bacterial spot thrives in warm and humid conditions, especially during periods of rainfall or overhead irrigation. The bacterium can overwinter in infected buds, bark, and cankers, leading to recurring infections in subsequent seasons.\n\n4. Proper identification and management of bacterial spot are crucial to minimize its impact on peach tree health and fruit quality.",

          //bacterial_spot_treat
          "1. متاثرہ پودے کے حصوں کو چھانٹ کر نکال دیں، بشمول شاخیں، ٹہنیوں اور پھل جو بیکٹیریل دھبوں کی علامات ظاہر کرتے ہیں۔ مزید پھیلاؤ کو روکنے کے لئے چھانٹا ہوا مواد کو باگ سے دور کر دیں.\n\n2. بیکٹیریل دھبوں کے انفیکشن سے بچنے کے لیے معطل موسم کے دوران تانبے پر مبنی بیکٹیریا کش ادویات کا اطلاق کریں۔ مناسب درخواست کی شرح اور وقت کے لئے کارخانہ دار کی ہدایات پر عمل کریں.\n\n3. ایسے ثقافتی طریقوں کو نافذ کریں جو درختوں کی اچھی صحت کو فروغ دیتے ہیں، جیسے کہ مناسب فاصلہ رکھنا، ہوا کی گردش کو بہتر بنانے کے لیے کٹائی کرنا اور ضرورت سے زیادہ نائٹروجن کھاد سے بچنا۔ یہ طرز عمل بیکٹیریل دھبوں کی نشوونما کے لیے کم سازگار ماحول پیدا کرنے میں مدد کرتے ہیں۔\n\n4. زیادہ آبپاشی سے بچیں، کیونکہ پودوں کو گیلا کرنے سے بیکٹیریل دھبوں کے انفیکشن کا خطرہ بڑھ جاتا ہے۔ اس کے بجائے، ڈرپ آبپاشی یا دیگر طریقوں کا استعمال کریں جو پتوں اور پھلوں پر نمی کو کم سے کم کرتے ہیں۔\n\n5. اگر بیماری کا دباؤ زیادہ ہو تو، بڑھتے ہوئے موسم کے دوران تانبے پر مبنی حفاظتی سپرے لگانے پر غور کریں۔ یہ سپرے بیکٹیریل دھبوں کے خلاف اضافی کنٹرول فراہم کرتے ہیں جب روک تھام کے طور پر یا بیماری کی پہلی علامات پر لگائی جائے۔\n\nاپنے علاقے اور باگ کے انتظام کے طریقوں کے مطابق مخصوص سفارشات اور رہنمائی کے لئے مقامی زرعی توسیع کے دفاتر یا ماہرین سے مشورہ کرنا یاد رکھیں.":
              "1. Prune and remove infected plant parts, including branches, twigs, and fruit showing symptoms of bacterial spot. Dispose of the pruned material away from the orchard to prevent further spread.\n\n2. Apply copper-based bactericides during the dormant season to protect against bacterial spot infection. Follow the manufacturer's instructions for proper application rates and timings.\n\n3. Implement cultural practices that promote good tree health, such as proper spacing, pruning to improve air circulation, and avoiding excessive nitrogen fertilization. These practices help create an environment less favorable for bacterial spot development.\n\n4. Avoid overhead irrigation, as wetting the foliage increases the risk of bacterial spot infection. Instead, utilize drip irrigation or other methods that minimize moisture on the leaves and fruit.\n\n5. If the disease pressure is high, consider applying protective copper-based sprays during the growing season. These sprays provide additional control against bacterial spot when applied preventatively or at the first signs of the disease.\n\nRemember to consult with local agricultural extension offices or experts for specific recommendations and guidance tailored to your region and orchard management practices.",
          "روزا": "Rosa",
          //rose_desc
          "1. گلاب مقبول پھول پودے ہیں جو روزا جینس سے تعلق رکھتے ہیں.\n\n2. وہ رنگ، سائز، اور خوشبو کی ایک وسیع رینج میں آتے ہیں.\n\n3. گلاب میں کانٹے دار تنے اور پرکشش، پرتوں والے پنکھے ہوتے ہیں۔\n\n4. یہ وسیع پیمانے پر سجاوٹ کے مقاصد کے لئے کاشت کی جاتی ہے اور اکثر باغات اور پھولوں کے انتظامات میں استعمال کیا جاتا ہے.\n\n5. گلاب کے علامتی معنی ہیں اور محبت، خوبصورتی اور رومانوی سے وابستہ ہیں۔":
              "1. Roses are popular flowering plants that belong to the Rosa genus.\n\n2. They come in a wide range of colors, sizes, and fragrances.\n\n3. Roses have thorny stems and attractive, layered petals.\n\n4. They are widely cultivated for ornamental purposes and are often used in gardens and floral arrangements.\n\n5. Roses have symbolic meanings and are associated with love, beauty, and romance.",
          "کالا دھبہ": "Black spot",
          //black_spot_desc
          "1. گلاب سیاہ دھبہ ایک عام اور وسیع پیمانے پر پھپھوندی کا مرض ہے جو گلاب کو متاثر کرتا ہے۔ یہ فطر ڈپلوکارپن روسے کی وجہ سے ہوتا ہے۔\n\n2. بیماری عام طور پر انفیکشن زدہ گلاب کے پتوں پر سیاہ یا گہرے بھورے دھبوں کے طور پر نمودار ہوتی ہے۔ یہ دھبے چھوٹے شروع ہو سکتے ہیں لیکن آہستہ آہستہ سائز میں بڑھ جاتے ہیں جس سے متاثرہ پتے زرد ہو جاتے ہیں اور بالآخر وقت سے پہلے گر جاتے ہیں۔ سنگین صورتوں میں، سیاہ دھبے اکٹھے ہو سکتے ہیں جس سے پت جھڑ اور گلاب کے پودے کمزور ہو جاتے ہیں۔\n\n3. گلاب سیاہ دھبے گرم اور نم حالات میں پھولتا ہے، خاص طور پر جب پودے لمبے عرصے تک گیلے رہتے ہیں۔ پھپھوندی گرے ہوئے پتوں پر سردیاں گزارتا ہے اور پانی کے چھینٹوں، بارش یا ہوا کے پھیلے ہوئے تخمک سے پھیل سکتا ہے۔\n\n4. گلاب سیاہ دھبے کے مؤثر انتظام میں ثقافتی طریقوں اور فطر کش ادویات کے علاج کا ایک مجموعہ شامل ہوتا ہے۔ صحت مند گلاب کو برقرار رکھنے کے لیے ابتدائی پتہ لگانے اور مسلسل کنٹرول کے اقدامات ضروری ہیں۔":
              "1. Rose black spot is a common and widespread fungal disease that affects roses. It is caused by the fungus Diplocarpon rosae.\n\n2. The disease typically appears as black or dark brown spots on the leaves of infected roses. These spots may start small but gradually increase in size, causing the affected leaves to turn yellow and eventually drop prematurely. In severe cases, the black spots can coalesce, leading to defoliation and weakening of the rose plant.\n\n3. Rose black spot thrives in warm and humid conditions, especially when foliage remains wet for prolonged periods. The fungus overwinters on fallen leaves and can spread through splashing water, rain, or wind-dispersed spores.\n\n4. Effective management of rose black spot involves a combination of cultural practices and fungicidal treatments. Early detection and consistent control measures are essential to maintain healthy roses.",
          //black_spot_treat
          "1. گلاب کی جھاڑیوں کے ارد گرد سے کسی بھی متاثرہ پتوں، کینوں یا پودے کے فضلے کو چھانٹ کر نکال دیں۔ مناسب حفظان صحت انوکولم کے ذریعہ کو کم کرنے اور مرض کے پھیلاؤ کو محدود کرنے میں مدد ملتی ہے۔\n\n2. گلاب کے پودوں کے ارد گرد اچھی ہوا کی گردش کو بہتر وقفہ کے لیے کٹائی کر کے اور کسی بھی زیادہ بھیڑ والی شاخوں کو ہٹا کر یقینی بنائیں۔ یہ پودوں کو تیزی سے خشک کرنے کو فروغ دیتا ہے اور سیاہ دھبوں کی نشوونما کے لیے سازگار حالات کو کم کرتا ہے۔\n\n3. بیس پر گلاب کو پانی دیں، زیادہ سے زیادہ آبپاشی سے گریز کریں۔ گیلے پتے پھپھوندی کے پھیلاؤ کو آسان بنا سکتے ہیں۔ پودوں کے اردگرد ملنا مٹی کی نمی کو برقرار رکھنے اور پتوں پر تخمک کے چھینٹوں کو روکنے میں بھی مدد کر سکتا ہے۔\n\n4. پھپھوندی مار دوا کو خاص طور پر گلاب پر سیاہ دھبوں کے کنٹرول کے لیے لیبل لگائیں۔ درخواست کی شرح اور وقت کے بارے میں مینوفیکچرر کی ہدایات پر عمل کریں. احتیاطی سے اسپرے کرنا شروع کریں، خاص طور پر زیادہ نمی کے دورانیے میں یا جب سیاہ دھبے موجود ہوں تو اسپرے کریں۔\n\n5. مزاحم گلاب کی انواع کو پودے لگانے پر غور کریں جو سیاہ دھبے کے لیے کم حساس ہوں۔ یہ انواع قدرتی مزاحمت کی سطح فراہم کرتی ہیں، جس سے کثرت سے فطر کش ادویات کے علاج کی ضرورت کو کم کیا جا سکتا ہے۔\n\nاپنے علاقے اور گلاب کی کاشت کے مطابق مخصوص فطر کش ادویات کی سفارشات اور ہدایات کے لئے مقامی گلاب ماہرین یا باغ مراکز سے مشورہ کریں۔":
              "1. Prune and remove any infected leaves, canes, or plant debris from around the rose bushes. Proper sanitation helps reduce the source of inoculum and limits the spread of the disease.\n\n2. Ensure good air circulation around the rose plants by pruning for better spacing and removing any overcrowded branches. This promotes faster drying of the foliage and reduces the favorable conditions for black spot development.\n\n3. Water the roses at the base, avoiding overhead irrigation. Wet foliage can facilitate the spread of the fungus. Mulching around the plants can also help maintain soil moisture and prevent splashing of spores onto the leaves.\n\n4. Apply fungicides specifically labeled for black spot control on roses. Follow the manufacturer's instructions regarding application rates and timings. Begin spraying preventatively, especially during periods of high humidity or when black spot is known to be present.\n\n5. Consider planting resistant rose varieties that are less susceptible to black spot. These varieties can provide a level of natural resistance, reducing the need for frequent fungicidal treatments.\n\nConsult with local rose experts or garden centers for specific fungicide recommendations and guidelines tailored to your region and rose cultivars.",
          "وائٹس": "Vitis",
          //grape_desc
          "1. انگور وہ پھل ہوتے ہیں جو وائٹس جینس کی داھلتاوں پر اگتے ہیں۔\n\n2. یہ بحیرہ روم کے علاقے کے مقامی ہیں اور اب دنیا بھر میں کاشت کی جاتی ہے۔\n\n3. انگور مختلف رنگوں میں آتے ہیں جن میں سبز، سرخ اور جامنی رنگ شامل ہیں۔\n\n4. انہیں اکثر تازہ استعمال کیا جاتا ہے یا شراب، جوس اور کشمش بنانے کے لیے استعمال کیا جاتا ہے۔\n\n5. انگور ینٹ، وٹامن، اور معدنیات کا ایک امیر ذریعہ ہیں.":
              "1. Grapes are fruits that grow on vines of the Vitis genus.\n\n2. They are native to the Mediterranean region and are now cultivated worldwide.\n\n3. Grapes come in various colors, including green, red, and purple.\n\n4. They are often consumed fresh or used for making wines, juices, and raisins.\n\n5. Grapes are a rich source of antioxidants, vitamins, and minerals.",
          //Black rot
          "سیاہ سڑنا": "Black rot",
          //black_rot_desc
          "1. انگور سیاہ سڑاند ایک پھپھوندی بیماری ہے جو گوئگنارڈیا بیڈویلی مرض زا کی وجہ سے ہوتا ہے۔ یہ انگور کی مختلف کاشت کو متاثر کرتا ہے اور پھلوں اور پھلوں دونوں کو کافی نقصان پہنچا سکتا ہے۔\n\n2. مرض انگور کے بیریوں، پتوں اور شاخوں پر چھوٹے، گہرے بھورے یا سیاہ گول زخموں کے طور پر ظاہر ہوتا ہے۔ یہ زخم بڑے ہو سکتے ہیں اور دھنسے ہوئے ہو سکتے ہیں جن کی خصوصیت 'مم' ظاہر ہوتی ہے۔ متاثرہ بیر اکثر سکڑتے ہیں اور سیاہ ہو جاتے ہیں جس کے نتیجے میں پھل شدید نقصان ہوتا ہے۔\n\n3. انگور کی سیاہ سڑاند گرم اور نم موسم میں پنپتی ہے۔ پھپھوندی متاثرہ پودے کے مواد میں سردیاں گزارتا ہے، جیسے کہ خشک بیریوں اور کینوں، اور موسم بہار میں بارش یا زیادہ نمی کے دوران تخمک خارج کرتا ہے۔\n\n4. انگور سیاہ سڑاند کی مناسب شناخت، نگرانی اور انتظام داھ کی حفاظت اور انگور کی پیداوار اور معیار کو محفوظ رکھنے کے لئے ضروری ہے.":
              "1. Grape black rot is a fungal disease caused by the pathogen Guignardia bidwellii. It affects various grape cultivars and can cause significant damage to both foliage and fruit.\n\n2. The disease manifests as small, dark brown or black circular lesions on grape berries, leaves, and stems. These lesions may enlarge and become sunken, with a characteristic 'mummified' appearance. Infected berries often shrivel and turn black, resulting in severe fruit loss.\n\n3. Grape black rot thrives in warm and humid climates. The fungus overwinters in infected plant material, such as dried berries and canes, and releases spores in spring during rainfall or high humidity.\n\n4. Proper identification, monitoring, and management of grape black rot are essential to protect vineyards and preserve grape yield and quality.",
          //black_rot_treat
          "1. داھ کی باری سے کسی بھی متاثرہ انگور کے گچھے، پتوں اور ڈانوں کو چھانٹ کر نکال دیں۔ مرض کے پھیلاؤ کو روکنے کے لیے چھانٹا ہوا مواد تباہ کر دیں۔ حفظان صحت کے مناسب طریقوں سے انوکولم ذریعہ کو کم کرنے میں مدد ملتی ہے.\n\n2. چھتری کے انتظام کی تکنیکوں کو نافذ کریں جو انگور کی بیل کی چھتری میں اچھی ہوا کی گردش اور سورج کی روشنی کے دخول کو فروغ دیتے ہیں۔ یہ نمی کی سطح کو کم کرتا ہے اور سیاہ سڑاند کی نشوونما کے لیے کم سازگار ماحول پیدا کرتا ہے۔\n\n3. انگور کی سیاہ سڑاند کے خلاف حفاظت کے لئے افزائش کے اہم مراحل کے دوران مناسب فطر کش ادویات کا اطلاق کریں۔ کیپٹن، میکلوبوٹانل، یا مینکوزیب جیسے فعال اجزاء پر مشتمل فطر کش ادویات عام طور پر استعمال کی جاتی ہیں۔ درخواست کی شرح اور وقت کے لئے کارخانہ دار کی ہدایات پر عمل کریں.\n\n4. انگور کی بیلوں کی بنیاد کے گرد گھاس اور گھاس کو ہٹا دیں، کیونکہ یہ سیاہ سڑاند پھپھوندی کو بند کر سکتے ہیں۔ ویڈ فری زون کو برقرار رکھنے سے انفیکشن کے امکانات کم ہو جاتے ہیں اور ہوا کی گردش میں بہتری آتی ہے۔\n\n5. سیاہ سڑاند کی ابتدائی علامات کے لیے انگور کے گچھے، پتوں اور شاخوں کی باقاعدہ نگرانی کریں۔ مزید پھیلاؤ کو روکنے کے لیے کسی بھی متاثرہ پودے کے مواد کو فوری طور پر ہٹا کر تباہ کر دیں۔\n\nاپنے انگور کی کاشت اور علاقائی حالات کے مطابق مخصوص فطر کش ادویات کی سفارشات اور ہدایات کے لئے مقامی ویٹی کلچر ماہرین یا زرعی توسیع کے دفاتر سے مشورہ کریں.":
              "1. Prune and remove any infected grape clusters, leaves, and canes from the vineyard. Destroy the pruned material to prevent the spread of the disease. Proper sanitation practices help reduce the inoculum source.\n\n2. Implement canopy management techniques that promote good air circulation and sunlight penetration into the grapevine canopy. This reduces humidity levels and creates an environment less favorable for black rot development.\n\n3. Apply appropriate fungicides during critical growth stages to protect against grape black rot. Fungicides containing active ingredients like captan, myclobutanil, or mancozeb are commonly used. Follow the manufacturer's instructions for application rates and timings.\n\n4. Remove weeds and grasses around the base of the grapevines, as they can harbor the black rot fungus. Maintaining weed-free zones reduces the chances of infection and improves air circulation.\n\n5. Practice regular monitoring of grape clusters, leaves, and stems for early signs of black rot. Promptly remove and destroy any infected plant material to prevent further spread.\n\nConsult with local viticulture experts or agricultural extension offices for specific fungicide recommendations and guidelines tailored to your grape cultivars and regional conditions."
        },
        'ur_PK': {
          "Welcome": "خوش آمدید",
          "Take Picture": "تصویر لیں",
          "Plant Encyclopedia": "پلانٹ انسائیکلو",
          "History": "ہسٹری",
          "Choose an option": "ایک اختیار منتخب کریں",
          "Camera": "کیمرا",
          "Gallery": "گیلری",
          "No plants found.": "کوئی پودے نہیں ملے۔",
          "History of Plants": "پودوں کی تاریخ",
          "No saved plants": "کوئی بچا ہوا پودا نہیں۔",
          "Plant Identified!": "پودے کی شناخت!",

          "Detect Disease": "بیماری کا پتہ لگانے",
          "Plant Identified & \nDisease Detected!":
              "پودے کی نشاندہی اور بیماری کا پتہ چلا!",
          "Identify Plant": "پلانٹ کی شناخت کریں",
          "Language Selection": "زبان کا انتخاب",
          "English": "انگریزی",
          "Urdu": "اردو",
          "No Disease Present!": "کوئی بیماری موجود نہیں!",
          "Plant Not Found!": "پلانٹ نہیں ملا!",
          "Plant Details": "پودوں کی تفصیلات",
          "Scientific Name": "سائنسی نام",
          "Description": "تفصیل",
          "Diseases": "امراض",
          "Disease Description": "بیماریوں کی تفصیل",
          "Treatments": "علاج",
          //tomato
          "Tomato": "ٹماٹر",
          "Solanum lycopersicum": "سولینم لائکوپرسیکم",
          //tomato descr
          "1. The tomato plant (Solanum lycopersicum) is a popular and versatile plant cultivated worldwide for its delicious and nutritious fruit.\n\n2. Tomato plants have a sprawling growth habit with vine-like stems that require support. The leaves are compound and typically green with a slightly hairy texture. The flowers are small, yellow, and usually self-pollinating.\n\n3. Tomatoes come in various sizes, shapes, and colors depending on the variety. The fruits develop after successful pollination and can be harvested when they reach maturity.\n\n4. To cultivate tomato plants successfully, it\\'s essential to consider factors such as soil preparation, watering, fertilizing, and pest control. Staking or pruning techniques may also be necessary for optimal growth and fruit production.":
              "1. ٹماٹر کا پودا (Solanum lycopersicum) ایک مقبول اور ورسٹائل پودا ہے جو دنیا بھر میں اپنے مزیدار اور غذائیت سے بھرپور پھل کے لئے کاشت کیا جاتا ہے۔\n\n2. ٹماٹر کے پودوں میں انگور جیسے تنوں کے ساتھ بہت زیادہ نشوونما کی عادت ہوتی ہے جن میں مدد کی ضرورت ہوتی ہے۔ پتے کمپاؤنڈ ہوتے ہیں اور عموماً ہلکے بالوں والی ساخت کے ساتھ سبز ہوتے ہیں۔ پھول چھوٹے، پیلے رنگ کے ہوتے ہیں اور عموماً خود آلودگی کرنے والے ہوتے ہیں۔\n\n3. ٹماٹر مختلف سائز، سائز، اور مختلف قسم کے لحاظ سے رنگوں میں آتے ہیں. پھل کامیاب زراعت کے بعد نشوونما پاتے ہیں اور جب یہ پختگی تک پہنچ جاتے ہیں تو کاشت کی جا سکتی ہے۔\n\n4. ٹماٹر کے پودوں کو کامیابی سے کاشت کرنے کے لئے، مٹی کی تیاری، پانی، کھاد اور کیڑوں پر قابو پانے جیسے عوامل پر غور کرنا ضروری ہے۔ زیادہ سے زیادہ نشوونما اور پھلوں کی پیداوار کے لئے سٹاکنگ یا کٹائی کی تکنیک بھی ضروری ہو سکتی ہے۔",
          "Late blight": "لیٹ بلائٹ",
          //late blight desc
          "1. Late blight is a destructive and highly contagious fungal disease that primarily affects tomatoes and potatoes. It is caused by the pathogen Phytophthora infestans.\n\n2. The disease commonly appears as dark, water-soaked lesions on leaves, stems, and fruits of infected plants. These lesions may rapidly enlarge, turn brown, and develop a fuzzy white mold growth on the undersides during humid conditions.\n\n3. Late blight thrives in cool and wet conditions, particularly during periods of high humidity and temperatures ranging from 50 to 80°F (10 to 27°C). Spores of the pathogen can spread rapidly through wind, rain, or movement of infected plant material.\n\n4. It is crucial to promptly identify and manage late blight to prevent severe crop damage. Control measures include removing and destroying infected plants, applying fungicides, maintaining proper spacing between plants, promoting good air circulation, and practicing crop rotation.":
              "1. لیٹ بلائٹ ایک تباہ کن اور انتہائی متعدی فطر کی بیماری ہے جو بنیادی طور پر ٹماٹر اور آلو کو متاثر کرتی ہے۔ یہ مرض زا فائٹوفتھورا انفیسٹنس کی وجہ سے ہوتا ہے۔\n\n2. مرض عام طور پر انفیکشن زدہ پودوں کے پتوں، تنوں اور پھلوں پر گہرے، پانی میں بھیگے ہوئے زخموں کے طور پر ظاہر ہوتا ہے۔ یہ زخم تیزی سے بڑے ہو سکتے ہیں، بھورے ہو سکتے ہیں اور نم حالات کے دوران نچلے حصے پر فجی سفید پھپھوندی کی نشوونما پیدا کرتے ہیں۔\n\n3. دیر سے مرجھانا ٹھنڈے اور گیلے حالات میں پھولتا ہے، خاص طور پر زیادہ نمی اور درجہ حرارت 50 سے 80° F (10 سے 27 ڈگری سینٹی گریڈ) کے دوران ہوتا ہے۔ مرض زا کے تخمک ہوا، بارش یا متاثرہ پودے کے مواد کی نقل و حرکت سے تیزی سے پھیل سکتے ہیں۔\n\n4. فصل کے شدید نقصان سے بچنے کے لئے فوری طور پر مرجھانے اور دیر سے مرجھانے کا انتظام کرنا انتہائی اہم ہے۔ کنٹرول کے اقدامات میں انفیکشن زدہ پودوں کو ہٹانا اور تباہ کرنا، فطر کش ادویات لگانا، پودوں کے درمیان مناسب وقفہ برقرار رکھنا، اچھی ہوا کی گردش کو فروغ دینا اور فصل کی گردش کی مشق شامل ہیں۔",
          //late blight treat
          "1. Promptly remove and destroy any infected plants, including leaves, stems, and fruits. This helps prevent the spread of the disease.\n\n2. Apply appropriate fungicides according to the manufacturer's instructions. Fungicides containing active ingredients like chlorothalonil, mancozeb, or copper can be effective against late blight. Follow the recommended application rates and timings.\n\n3. Ensure proper spacing between plants to promote good air circulation. This reduces humidity levels and creates an environment less favorable for the development and spread of late blight.\n\n4. Practice crop rotation by avoiding planting tomatoes or potatoes in the same location for consecutive years. This helps break the disease cycle as the pathogen cannot survive without a suitable host plant.\n\nRemember to regularly monitor your plants for any signs of late blight and take action promptly if detected. Early intervention is crucial to prevent severe damage and minimize the spread of the disease.":
              "1. کسی بھی متاثرہ پودوں کو فوری طور پر ہٹا دیں اور تباہ کر دیں، بشمول پتے، تنوں اور پھلوں کو تباہ کر دیں۔ اس سے بیماری کے پھیلاؤ کو روکنے میں مدد ملتی ہے۔\n\n2. صنعت کار کی ہدایات کے مطابق مناسب فطر کش ادویات کا اطلاق کریں۔ کلوروتھالونل، مینکوزیب یا تانبے جیسے فعال اجزاء پر مشتمل فطر کش ادویات دیر سے مرجھانے کے خلاف مؤثر ثابت ہو سکتی ہیں۔ سفارش کی درخواست کی شرح اور اوقات پر عمل کریں.\n\n3. اچھی ہوا کی گردش کو فروغ دینے کے لئے پودوں کے درمیان مناسب وقفہ کو یقینی بنائیں. یہ نمی کی سطح کو کم کرتا ہے اور دیر سے مرجھانے کی نشوونما اور پھیلاؤ کے لئے کم سازگار ماحول پیدا کرتا ہے.\n\n4. مسلسل برسوں تک ایک ہی مقام پر ٹماٹر یا آلو لگانے سے گریز کر کے فصل کی گردش کی مشق کریں۔ یہ بیماری کے چکر کو توڑنے میں مدد کرتا ہے کیونکہ مرض زا کسی مناسب میزبان پودے کے بغیر زندہ نہیں رہ سکتا۔\n\nباقاعدگی سے دیر سے بلائٹ کے کسی بھی علامات کے لئے اپنے پودوں کی نگرانی اور پتہ چلا ہے تو فوری طور پر کارروائی کرنے کے لئے یاد رکھیں. شدید نقصان سے بچنے اور بیماری کے پھیلاؤ کو کم کرنے کے لیے ابتدائی مداخلت انتہائی اہم ہے۔",
          "Peach": "آڑو",
          "Rose": "گلاب",
          "Grape": "انگور",
          "Prunus persica": "پرونس پرسیکا",
          //peach desc
          "1. Peaches are juicy and delicious fruits that belong to the Prunus genus.\n\n2. They are native to China and are now cultivated in various parts of the world.\n\n3.Peaches have a soft, fuzzy skin, and their flesh is sweet and aromatic.\n\n4. They come in different varieties, including clingstone and freestone.\n\n5. Peaches are rich in vitamins A and C and are a good source of dietary fiber.":
              "1. آڑو رسیلی اور مزیدار پھل ہیں جو پرونس جینس سے تعلق رکھتے ہیں.\n\n2. یہ چین کے مقامی ہیں اور اب دنیا کے مختلف حصوں میں کاشت کی جاتی ہے۔\n\n3. پیچ ایک نرم، فجی جلد ہے، اور ان کا گوشت میٹھا اور کھشبودار ہے.\n\n4. یہ مختلف قسموں میں آتے ہیں جن میں کلنگسٹون اور فریسٹون شامل ہیں۔\n\n5. آڑو وٹامن اے اور سی میں امیر ہیں اور غذائی فائبر کا ایک اچھا ذریعہ ہیں.",

          "Bacterial spot": "بیکٹیریل اسپاٹ",

          //bacterial_spot_desc
          "1. Bacterial spot is a common and destructive disease that affects peach trees. It is caused by the bacterium Xanthomonas arboricola pv. pruni.\n\n2. The disease typically manifests as small, dark spots on the leaves, fruits, and twigs of infected peach trees. These spots may have a water-soaked appearance and can enlarge over time. As the disease progresses, the spots develop a raised, corky texture and may lead to premature leaf drop and fruit rot.\n\n3. Bacterial spot thrives in warm and humid conditions, especially during periods of rainfall or overhead irrigation. The bacterium can overwinter in infected buds, bark, and cankers, leading to recurring infections in subsequent seasons.\n\n4. Proper identification and management of bacterial spot are crucial to minimize its impact on peach tree health and fruit quality.":
              "1. بیکٹیریل دھبے ایک عام اور تباہ کن بیماری ہے جو آڑو کے درختوں کو متاثر کرتی ہے۔ یہ بیکٹیریم زینتھوموناس آربوریکولا پی وی پرانی کی وجہ سے ہوتا ہے۔\n\n2. بیماری عموماً پتوں، پھلوں اور متاثرہ آڑو کے درختوں پر چھوٹے، سیاہ دھبوں کے طور پر ظاہر ہوتی ہے۔ ان دھبوں میں پانی میں بھیگے ہوئے ظہور ہو سکتے ہیں اور وقت کے ساتھ ساتھ بڑے ہو سکتے ہیں۔ جیسے جیسے مرض بڑھتا ہے، دھبے ابھرتی ہوئی، کارکی ساخت بنتے ہیں اور پتے کے قبل از وقت گرنے اور پھلوں کی سڑاند کا سبب بنتے ہیں۔\n\n3. بیکٹیریل دھبے گرم اور نم حالات میں پھولتے ہیں، خاص طور پر بارش یا زیادہ آبپاشی کے دوران۔ بیکٹیریم انفیکشن زدہ کلیوں، چھال اور کینکروں میں سردیاں گزار سکتا ہے جس سے بعد کے موسموں میں بار بار ہونے والے انفیکشنز پیدا ہوتے ہیں۔\n\n4. آڑو کے درختوں کی صحت اور پھل کے معیار پر اس کے اثرات کو کم کرنے کے لئے بیکٹیریل دھبوں کی مناسب شناخت اور انتظام اہم ہے۔",

          //bacterial_spot_treat
          "1. Prune and remove infected plant parts, including branches, twigs, and fruit showing symptoms of bacterial spot. Dispose of the pruned material away from the orchard to prevent further spread.\n\n2. Apply copper-based bactericides during the dormant season to protect against bacterial spot infection. Follow the manufacturer's instructions for proper application rates and timings.\n\n3. Implement cultural practices that promote good tree health, such as proper spacing, pruning to improve air circulation, and avoiding excessive nitrogen fertilization. These practices help create an environment less favorable for bacterial spot development.\n\n4. Avoid overhead irrigation, as wetting the foliage increases the risk of bacterial spot infection. Instead, utilize drip irrigation or other methods that minimize moisture on the leaves and fruit.\n\n5. If the disease pressure is high, consider applying protective copper-based sprays during the growing season. These sprays provide additional control against bacterial spot when applied preventatively or at the first signs of the disease.\n\nRemember to consult with local agricultural extension offices or experts for specific recommendations and guidance tailored to your region and orchard management practices.":
              "1. متاثرہ پودے کے حصوں کو چھانٹ کر نکال دیں، بشمول شاخیں، ٹہنیوں اور پھل جو بیکٹیریل دھبوں کی علامات ظاہر کرتے ہیں۔ مزید پھیلاؤ کو روکنے کے لئے چھانٹا ہوا مواد کو باگ سے دور کر دیں.\n\n2. بیکٹیریل دھبوں کے انفیکشن سے بچنے کے لیے معطل موسم کے دوران تانبے پر مبنی بیکٹیریا کش ادویات کا اطلاق کریں۔ مناسب درخواست کی شرح اور وقت کے لئے کارخانہ دار کی ہدایات پر عمل کریں.\n\n3. ایسے ثقافتی طریقوں کو نافذ کریں جو درختوں کی اچھی صحت کو فروغ دیتے ہیں، جیسے کہ مناسب فاصلہ رکھنا، ہوا کی گردش کو بہتر بنانے کے لیے کٹائی کرنا اور ضرورت سے زیادہ نائٹروجن کھاد سے بچنا۔ یہ طرز عمل بیکٹیریل دھبوں کی نشوونما کے لیے کم سازگار ماحول پیدا کرنے میں مدد کرتے ہیں۔\n\n4. زیادہ آبپاشی سے بچیں، کیونکہ پودوں کو گیلا کرنے سے بیکٹیریل دھبوں کے انفیکشن کا خطرہ بڑھ جاتا ہے۔ اس کے بجائے، ڈرپ آبپاشی یا دیگر طریقوں کا استعمال کریں جو پتوں اور پھلوں پر نمی کو کم سے کم کرتے ہیں۔\n\n5. اگر بیماری کا دباؤ زیادہ ہو تو، بڑھتے ہوئے موسم کے دوران تانبے پر مبنی حفاظتی سپرے لگانے پر غور کریں۔ یہ سپرے بیکٹیریل دھبوں کے خلاف اضافی کنٹرول فراہم کرتے ہیں جب روک تھام کے طور پر یا بیماری کی پہلی علامات پر لگائی جائے۔\n\nاپنے علاقے اور باگ کے انتظام کے طریقوں کے مطابق مخصوص سفارشات اور رہنمائی کے لئے مقامی زرعی توسیع کے دفاتر یا ماہرین سے مشورہ کرنا یاد رکھیں.",
          "Rosa": "روزا",
          //rose_desc
          "1. Roses are popular flowering plants that belong to the Rosa genus.\n\n2. They come in a wide range of colors, sizes, and fragrances.\n\n3. Roses have thorny stems and attractive, layered petals.\n\n4. They are widely cultivated for ornamental purposes and are often used in gardens and floral arrangements.\n\n5. Roses have symbolic meanings and are associated with love, beauty, and romance.":
              "1. گلاب مقبول پھول پودے ہیں جو روزا جینس سے تعلق رکھتے ہیں.\n\n2. وہ رنگ، سائز، اور خوشبو کی ایک وسیع رینج میں آتے ہیں.\n\n3. گلاب میں کانٹے دار تنے اور پرکشش، پرتوں والے پنکھے ہوتے ہیں۔\n\n4. یہ وسیع پیمانے پر سجاوٹ کے مقاصد کے لئے کاشت کی جاتی ہے اور اکثر باغات اور پھولوں کے انتظامات میں استعمال کیا جاتا ہے.\n\n5. گلاب کے علامتی معنی ہیں اور محبت، خوبصورتی اور رومانوی سے وابستہ ہیں۔",
          "Black spot": "کالا دھبہ",
          //black_spot_desc
          "1. Rose black spot is a common and widespread fungal disease that affects roses. It is caused by the fungus Diplocarpon rosae.\n\n2. The disease typically appears as black or dark brown spots on the leaves of infected roses. These spots may start small but gradually increase in size, causing the affected leaves to turn yellow and eventually drop prematurely. In severe cases, the black spots can coalesce, leading to defoliation and weakening of the rose plant.\n\n3. Rose black spot thrives in warm and humid conditions, especially when foliage remains wet for prolonged periods. The fungus overwinters on fallen leaves and can spread through splashing water, rain, or wind-dispersed spores.\n\n4. Effective management of rose black spot involves a combination of cultural practices and fungicidal treatments. Early detection and consistent control measures are essential to maintain healthy roses.":
              "1. گلاب سیاہ دھبہ ایک عام اور وسیع پیمانے پر پھپھوندی کا مرض ہے جو گلاب کو متاثر کرتا ہے۔ یہ فطر ڈپلوکارپن روسے کی وجہ سے ہوتا ہے۔\n\n2. بیماری عام طور پر انفیکشن زدہ گلاب کے پتوں پر سیاہ یا گہرے بھورے دھبوں کے طور پر نمودار ہوتی ہے۔ یہ دھبے چھوٹے شروع ہو سکتے ہیں لیکن آہستہ آہستہ سائز میں بڑھ جاتے ہیں جس سے متاثرہ پتے زرد ہو جاتے ہیں اور بالآخر وقت سے پہلے گر جاتے ہیں۔ سنگین صورتوں میں، سیاہ دھبے اکٹھے ہو سکتے ہیں جس سے پت جھڑ اور گلاب کے پودے کمزور ہو جاتے ہیں۔\n\n3. گلاب سیاہ دھبے گرم اور نم حالات میں پھولتا ہے، خاص طور پر جب پودے لمبے عرصے تک گیلے رہتے ہیں۔ پھپھوندی گرے ہوئے پتوں پر سردیاں گزارتا ہے اور پانی کے چھینٹوں، بارش یا ہوا کے پھیلے ہوئے تخمک سے پھیل سکتا ہے۔\n\n4. گلاب سیاہ دھبے کے مؤثر انتظام میں ثقافتی طریقوں اور فطر کش ادویات کے علاج کا ایک مجموعہ شامل ہوتا ہے۔ صحت مند گلاب کو برقرار رکھنے کے لیے ابتدائی پتہ لگانے اور مسلسل کنٹرول کے اقدامات ضروری ہیں۔",
          //black_spot_treat
          "1. Prune and remove any infected leaves, canes, or plant debris from around the rose bushes. Proper sanitation helps reduce the source of inoculum and limits the spread of the disease.\n\n2. Ensure good air circulation around the rose plants by pruning for better spacing and removing any overcrowded branches. This promotes faster drying of the foliage and reduces the favorable conditions for black spot development.\n\n3. Water the roses at the base, avoiding overhead irrigation. Wet foliage can facilitate the spread of the fungus. Mulching around the plants can also help maintain soil moisture and prevent splashing of spores onto the leaves.\n\n4. Apply fungicides specifically labeled for black spot control on roses. Follow the manufacturer's instructions regarding application rates and timings. Begin spraying preventatively, especially during periods of high humidity or when black spot is known to be present.\n\n5. Consider planting resistant rose varieties that are less susceptible to black spot. These varieties can provide a level of natural resistance, reducing the need for frequent fungicidal treatments.\n\nConsult with local rose experts or garden centers for specific fungicide recommendations and guidelines tailored to your region and rose cultivars.":
              "1. گلاب کی جھاڑیوں کے ارد گرد سے کسی بھی متاثرہ پتوں، کینوں یا پودے کے فضلے کو چھانٹ کر نکال دیں۔ مناسب حفظان صحت انوکولم کے ذریعہ کو کم کرنے اور مرض کے پھیلاؤ کو محدود کرنے میں مدد ملتی ہے۔\n\n2. گلاب کے پودوں کے ارد گرد اچھی ہوا کی گردش کو بہتر وقفہ کے لیے کٹائی کر کے اور کسی بھی زیادہ بھیڑ والی شاخوں کو ہٹا کر یقینی بنائیں۔ یہ پودوں کو تیزی سے خشک کرنے کو فروغ دیتا ہے اور سیاہ دھبوں کی نشوونما کے لیے سازگار حالات کو کم کرتا ہے۔\n\n3. بیس پر گلاب کو پانی دیں، زیادہ سے زیادہ آبپاشی سے گریز کریں۔ گیلے پتے پھپھوندی کے پھیلاؤ کو آسان بنا سکتے ہیں۔ پودوں کے اردگرد ملنا مٹی کی نمی کو برقرار رکھنے اور پتوں پر تخمک کے چھینٹوں کو روکنے میں بھی مدد کر سکتا ہے۔\n\n4. پھپھوندی مار دوا کو خاص طور پر گلاب پر سیاہ دھبوں کے کنٹرول کے لیے لیبل لگائیں۔ درخواست کی شرح اور وقت کے بارے میں مینوفیکچرر کی ہدایات پر عمل کریں. احتیاطی سے اسپرے کرنا شروع کریں، خاص طور پر زیادہ نمی کے دورانیے میں یا جب سیاہ دھبے موجود ہوں تو اسپرے کریں۔\n\n5. مزاحم گلاب کی انواع کو پودے لگانے پر غور کریں جو سیاہ دھبے کے لیے کم حساس ہوں۔ یہ انواع قدرتی مزاحمت کی سطح فراہم کرتی ہیں، جس سے کثرت سے فطر کش ادویات کے علاج کی ضرورت کو کم کیا جا سکتا ہے۔\n\nاپنے علاقے اور گلاب کی کاشت کے مطابق مخصوص فطر کش ادویات کی سفارشات اور ہدایات کے لئے مقامی گلاب ماہرین یا باغ مراکز سے مشورہ کریں۔",
          "Vitis": "وائٹس",
          //grape_desc
          "1. Grapes are fruits that grow on vines of the Vitis genus.\n\n2. They are native to the Mediterranean region and are now cultivated worldwide.\n\n3. Grapes come in various colors, including green, red, and purple.\n\n4. They are often consumed fresh or used for making wines, juices, and raisins.\n\n5. Grapes are a rich source of antioxidants, vitamins, and minerals.":
              "1. انگور وہ پھل ہوتے ہیں جو وائٹس جینس کی داھلتاوں پر اگتے ہیں۔\n\n2. یہ بحیرہ روم کے علاقے کے مقامی ہیں اور اب دنیا بھر میں کاشت کی جاتی ہے۔\n\n3. انگور مختلف رنگوں میں آتے ہیں جن میں سبز، سرخ اور جامنی رنگ شامل ہیں۔\n\n4. انہیں اکثر تازہ استعمال کیا جاتا ہے یا شراب، جوس اور کشمش بنانے کے لیے استعمال کیا جاتا ہے۔\n\n5. انگور ینٹ، وٹامن، اور معدنیات کا ایک امیر ذریعہ ہیں.",
          //Black rot
          "Black rot": "سیاہ سڑنا",
          //black_rot_desc
          "1. Grape black rot is a fungal disease caused by the pathogen Guignardia bidwellii. It affects various grape cultivars and can cause significant damage to both foliage and fruit.\n\n2. The disease manifests as small, dark brown or black circular lesions on grape berries, leaves, and stems. These lesions may enlarge and become sunken, with a characteristic 'mummified' appearance. Infected berries often shrivel and turn black, resulting in severe fruit loss.\n\n3. Grape black rot thrives in warm and humid climates. The fungus overwinters in infected plant material, such as dried berries and canes, and releases spores in spring during rainfall or high humidity.\n\n4. Proper identification, monitoring, and management of grape black rot are essential to protect vineyards and preserve grape yield and quality.":
              "1. انگور سیاہ سڑاند ایک پھپھوندی بیماری ہے جو گوئگنارڈیا بیڈویلی مرض زا کی وجہ سے ہوتا ہے۔ یہ انگور کی مختلف کاشت کو متاثر کرتا ہے اور پھلوں اور پھلوں دونوں کو کافی نقصان پہنچا سکتا ہے۔\n\n2. مرض انگور کے بیریوں، پتوں اور شاخوں پر چھوٹے، گہرے بھورے یا سیاہ گول زخموں کے طور پر ظاہر ہوتا ہے۔ یہ زخم بڑے ہو سکتے ہیں اور دھنسے ہوئے ہو سکتے ہیں جن کی خصوصیت 'مم' ظاہر ہوتی ہے۔ متاثرہ بیر اکثر سکڑتے ہیں اور سیاہ ہو جاتے ہیں جس کے نتیجے میں پھل شدید نقصان ہوتا ہے۔\n\n3. انگور کی سیاہ سڑاند گرم اور نم موسم میں پنپتی ہے۔ پھپھوندی متاثرہ پودے کے مواد میں سردیاں گزارتا ہے، جیسے کہ خشک بیریوں اور کینوں، اور موسم بہار میں بارش یا زیادہ نمی کے دوران تخمک خارج کرتا ہے۔\n\n4. انگور سیاہ سڑاند کی مناسب شناخت، نگرانی اور انتظام داھ کی حفاظت اور انگور کی پیداوار اور معیار کو محفوظ رکھنے کے لئے ضروری ہے.",
          //black_rot_treat
          "1. Prune and remove any infected grape clusters, leaves, and canes from the vineyard. Destroy the pruned material to prevent the spread of the disease. Proper sanitation practices help reduce the inoculum source.\n\n2. Implement canopy management techniques that promote good air circulation and sunlight penetration into the grapevine canopy. This reduces humidity levels and creates an environment less favorable for black rot development.\n\n3. Apply appropriate fungicides during critical growth stages to protect against grape black rot. Fungicides containing active ingredients like captan, myclobutanil, or mancozeb are commonly used. Follow the manufacturer's instructions for application rates and timings.\n\n4. Remove weeds and grasses around the base of the grapevines, as they can harbor the black rot fungus. Maintaining weed-free zones reduces the chances of infection and improves air circulation.\n\n5. Practice regular monitoring of grape clusters, leaves, and stems for early signs of black rot. Promptly remove and destroy any infected plant material to prevent further spread.\n\nConsult with local viticulture experts or agricultural extension offices for specific fungicide recommendations and guidelines tailored to your grape cultivars and regional conditions.":
              "1. داھ کی باری سے کسی بھی متاثرہ انگور کے گچھے، پتوں اور ڈانوں کو چھانٹ کر نکال دیں۔ مرض کے پھیلاؤ کو روکنے کے لیے چھانٹا ہوا مواد تباہ کر دیں۔ حفظان صحت کے مناسب طریقوں سے انوکولم ذریعہ کو کم کرنے میں مدد ملتی ہے.\n\n2. چھتری کے انتظام کی تکنیکوں کو نافذ کریں جو انگور کی بیل کی چھتری میں اچھی ہوا کی گردش اور سورج کی روشنی کے دخول کو فروغ دیتے ہیں۔ یہ نمی کی سطح کو کم کرتا ہے اور سیاہ سڑاند کی نشوونما کے لیے کم سازگار ماحول پیدا کرتا ہے۔\n\n3. انگور کی سیاہ سڑاند کے خلاف حفاظت کے لئے افزائش کے اہم مراحل کے دوران مناسب فطر کش ادویات کا اطلاق کریں۔ کیپٹن، میکلوبوٹانل، یا مینکوزیب جیسے فعال اجزاء پر مشتمل فطر کش ادویات عام طور پر استعمال کی جاتی ہیں۔ درخواست کی شرح اور وقت کے لئے کارخانہ دار کی ہدایات پر عمل کریں.\n\n4. انگور کی بیلوں کی بنیاد کے گرد گھاس اور گھاس کو ہٹا دیں، کیونکہ یہ سیاہ سڑاند پھپھوندی کو بند کر سکتے ہیں۔ ویڈ فری زون کو برقرار رکھنے سے انفیکشن کے امکانات کم ہو جاتے ہیں اور ہوا کی گردش میں بہتری آتی ہے۔\n\n5. سیاہ سڑاند کی ابتدائی علامات کے لیے انگور کے گچھے، پتوں اور شاخوں کی باقاعدہ نگرانی کریں۔ مزید پھیلاؤ کو روکنے کے لیے کسی بھی متاثرہ پودے کے مواد کو فوری طور پر ہٹا کر تباہ کر دیں۔\n\nاپنے انگور کی کاشت اور علاقائی حالات کے مطابق مخصوص فطر کش ادویات کی سفارشات اور ہدایات کے لئے مقامی ویٹی کلچر ماہرین یا زرعی توسیع کے دفاتر سے مشورہ کریں."
        }
      };
}
